language: php

php:
  - 7.4
  - 8.0

before_script:
  - sudo apt-get update
  - sudo apt-get install libfcgi0ldbl
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm

before_install:
  - composer self-update

install:
  #- composer install --no-interaction --prefer-source
  - composer install --no-interaction --prefer-source --ignore-platform-reqs # --ignore-platform-reqs because of consistence/coding-standard

script:
  - composer phpcs
  - composer phpstan
  - composer tests
